import { SmartMenuTemplate, LiveCounterAddon, MenuItemOption } from "./types";

export const MENU_ITEMS_MASTER: Record<string, MenuItemOption> = {
  // Welcome Drinks
  "wd-fruit-punch": {
    id: "wd-fruit-punch",
    name: "Exotic Fruit Punch Cooler",
    category: "Welcome Drink",
    dietary: "VEG",
    description: "Chilled blend of fresh pineapple, orange, and passion fruit with crushed ice.",
    basePortionPerPax: 0.18,
    portionUnit: "L",
    approxCostPerPax: 22,
    spiceLevel: "MILD",
    tags: ["beverage", "refreshing", "chilled"],
  },
  "wd-badam-milk": {
    id: "wd-badam-milk",
    name: "Royal Kesari Badam Milk",
    category: "Welcome Drink",
    dietary: "VEG",
    description: "Slow-simmered almond milk infused with pure saffron strands and cardamom.",
    basePortionPerPax: 0.15,
    portionUnit: "L",
    approxCostPerPax: 38,
    spiceLevel: "MILD",
    tags: ["beverage", "rich", "almond", "traditional"],
  },
  "wd-mango-lassi": {
    id: "wd-mango-lassi",
    name: "Alphonso Mango Lassi",
    category: "Welcome Drink",
    dietary: "VEG",
    description: "Thick hand-churned yogurt smoothie blended with ripe Alphonso mango pulp.",
    basePortionPerPax: 0.18,
    portionUnit: "L",
    approxCostPerPax: 30,
    spiceLevel: "MILD",
    tags: ["beverage", "creamy", "mango"],
  },
  "wd-mint-cooler": {
    id: "wd-mint-cooler",
    name: "Fresh Mint & Lemon Cooler",
    category: "Welcome Drink",
    dietary: "VEG",
    description: "Freshly squeezed lemon with crushed garden mint and rock salt.",
    basePortionPerPax: 0.2,
    portionUnit: "L",
    approxCostPerPax: 15,
    spiceLevel: "MILD",
    tags: ["beverage", "light", "digestive"],
  },

  // Starters
  "str-chicken-65": {
    id: "str-chicken-65",
    name: "Hyderabadi Chicken 65",
    category: "Starter",
    dietary: "NON_VEG",
    description: "Spiced crispy chicken bites tossed with fresh curry leaves, green chilies, and yogurt.",
    basePortionPerPax: 0.12,
    portionUnit: "kg",
    approxCostPerPax: 55,
    spiceLevel: "SPICY",
    tags: ["chicken", "signature", "crispy"],
  },
  "str-paneer-tikka": {
    id: "str-paneer-tikka",
    name: "Tandoori Paneer Tikka",
    category: "Starter",
    dietary: "VEG",
    description: "Char-grilled fresh cottage cheese cubes marinated in mustard oil, ajwain, and Kashmiri chili.",
    basePortionPerPax: 0.12,
    portionUnit: "kg",
    approxCostPerPax: 48,
    spiceLevel: "MEDIUM",
    tags: ["paneer", "tandoori", "starter"],
  },
  "str-apollo-fish": {
    id: "str-apollo-fish",
    name: "Spicy Apollo Fish Bites",
    category: "Starter",
    dietary: "NON_VEG",
    description: "Boneless freshwater fish fillet strips tossed in fiery Andhra red chili temper.",
    basePortionPerPax: 0.11,
    portionUnit: "kg",
    approxCostPerPax: 65,
    spiceLevel: "SPICY",
    tags: ["seafood", "fish", "spicy"],
  },
  "str-veg-spring-roll": {
    id: "str-veg-spring-roll",
    name: "Crispy Vegetable Spring Rolls",
    category: "Starter",
    dietary: "VEG",
    description: "Golden rolls stuffed with julienned cabbage, bell peppers, carrots, and glass noodles.",
    basePortionPerPax: 2,
    portionUnit: "pcs",
    approxCostPerPax: 28,
    spiceLevel: "MILD",
    tags: ["veg", "crispy"],
  },
  "str-corn-pepper": {
    id: "str-corn-pepper",
    name: "Crispy Salt & Pepper Corn",
    category: "Starter",
    dietary: "VEG",
    description: "Sweet American corn kernels batter-fried and tossed with spring onions and cracked black pepper.",
    basePortionPerPax: 0.1,
    portionUnit: "kg",
    approxCostPerPax: 25,
    spiceLevel: "MEDIUM",
    tags: ["veg", "corn", "crunchy"],
  },

  // Biryani & Rice
  "bir-chicken-dum": {
    id: "bir-chicken-dum",
    name: "Royal Hyderabadi Chicken Dum Biryani",
    category: "Biryani",
    dietary: "NON_VEG",
    description: "Aged long-grain Basmati rice slow-steamed with bone-in tender chicken, saffron, and pure cow ghee.",
    basePortionPerPax: 0.35,
    portionUnit: "kg",
    approxCostPerPax: 85,
    spiceLevel: "MEDIUM",
    tags: ["biryani", "chicken", "signature", "carb-heavy"],
  },
  "bir-mutton-dum": {
    id: "bir-mutton-dum",
    name: "Nawabi Mutton Dum Biryani",
    category: "Biryani",
    dietary: "NON_VEG",
    description: "Heritage clay-pot dum biryani prepared with select young goat meat and caramelized onions.",
    basePortionPerPax: 0.35,
    portionUnit: "kg",
    approxCostPerPax: 135,
    spiceLevel: "SPICY",
    tags: ["biryani", "mutton", "luxury", "carb-heavy"],
  },
  "bir-veg-dum": {
    id: "bir-veg-dum",
    name: "Shahi Vegetable Dum Biryani",
    category: "Biryani",
    dietary: "VEG",
    description: "Fragrant basmati rice cooked with fresh seasonal vegetables, mint, and saffron milk.",
    basePortionPerPax: 0.3,
    portionUnit: "kg",
    approxCostPerPax: 45,
    spiceLevel: "MEDIUM",
    tags: ["biryani", "veg", "carb-heavy"],
  },
  "rc-bagara": {
    id: "rc-bagara",
    name: "Telangana Bagara Rice",
    category: "Biryani",
    dietary: "VEG",
    description: "Basmati rice tempered with whole spices (cinnamon, cloves, cardamom, bay leaves) and caramelized onions.",
    basePortionPerPax: 0.25,
    portionUnit: "kg",
    approxCostPerPax: 32,
    spiceLevel: "MILD",
    tags: ["rice", "aromatic", "carb-heavy"],
  },

  // Breads
  "brd-butter-naan": {
    id: "brd-butter-naan",
    name: "Tandoori Butter Naan",
    category: "Breads",
    dietary: "VEG",
    description: "Soft leavened clay-oven flatbread brushed with pure melted butter.",
    basePortionPerPax: 1.5,
    portionUnit: "pcs",
    approxCostPerPax: 18,
    spiceLevel: "MILD",
    tags: ["bread", "tandoori"],
  },
  "brd-rumali": {
    id: "brd-rumali",
    name: "Handkerchief Rumali Roti",
    category: "Breads",
    dietary: "VEG",
    description: "Ultra-thin, soft handkerchief roti tossed over an inverted dome tawa.",
    basePortionPerPax: 2,
    portionUnit: "pcs",
    approxCostPerPax: 16,
    spiceLevel: "MILD",
    tags: ["bread", "soft"],
  },

  // Curries & Gravies
  "cur-butter-chicken": {
    id: "cur-butter-chicken",
    name: "Creamy Murgh Makhani (Butter Chicken)",
    category: "Curry",
    dietary: "NON_VEG",
    description: "Tandoori chicken tikkas simmered in a velvety tomato, cashew, and honey butter gravy.",
    basePortionPerPax: 0.15,
    portionUnit: "kg",
    approxCostPerPax: 65,
    spiceLevel: "MILD",
    tags: ["chicken", "gravy", "creamy"],
  },
  "cur-paneer-butter-masala": {
    id: "cur-paneer-butter-masala",
    name: "Paneer Butter Masala",
    category: "Curry",
    dietary: "VEG",
    description: "Tender paneer cubes cooked in a rich, buttery tomato sauce infused with kasuri methi.",
    basePortionPerPax: 0.15,
    portionUnit: "kg",
    approxCostPerPax: 48,
    spiceLevel: "MILD",
    tags: ["paneer", "gravy", "sweet-tangy"],
  },
  "cur-kadai-paneer": {
    id: "cur-kadai-paneer",
    name: "Kadai Paneer Bell Pepper Toss",
    category: "Curry",
    dietary: "VEG",
    description: "Cottage cheese chunks and bell peppers simmered in a freshly pounded coriander and red chili masala.",
    basePortionPerPax: 0.15,
    portionUnit: "kg",
    approxCostPerPax: 46,
    spiceLevel: "SPICY",
    tags: ["paneer", "gravy", "spicy"],
  },
  "cur-veg-kolhapuri": {
    id: "cur-veg-kolhapuri",
    name: "Spicy Veg Kolhapuri Melange",
    category: "Curry",
    dietary: "VEG",
    description: "Garden fresh carrots, beans, peas, and florets cooked in a fiery roasted coconut-sesame gravy.",
    basePortionPerPax: 0.15,
    portionUnit: "kg",
    approxCostPerPax: 32,
    spiceLevel: "SPICY",
    tags: ["veg", "gravy", "spicy", "alternative"],
  },
  "cur-dal-makhani": {
    id: "cur-dal-makhani",
    name: "Peshawari Dal Makhani",
    category: "Curry",
    dietary: "VEG",
    description: "Black urad lentils and red kidney beans slow-cooked for 18 hours with white butter and cream.",
    basePortionPerPax: 0.15,
    portionUnit: "kg",
    approxCostPerPax: 28,
    spiceLevel: "MILD",
    tags: ["dal", "gravy", "rich"],
  },

  // Traditional Rice & Dal
  "rc-steamed-rice": {
    id: "rc-steamed-rice",
    name: "Steamed Sona Masoori Rice",
    category: "Rice",
    dietary: "VEG",
    description: "Fluffy steamed premium Andhra Sona Masoori rice served with hot pure ghee.",
    basePortionPerPax: 0.18,
    portionUnit: "kg",
    approxCostPerPax: 14,
    spiceLevel: "MILD",
    tags: ["rice", "plain", "carb-heavy"],
  },
  "dal-tomato-pappu": {
    id: "dal-tomato-pappu",
    name: "Andhra Tomato Pappu (Dal)",
    category: "Dal",
    dietary: "VEG",
    description: "Yellow toor dal tempered with ripe country tomatoes, mustard seeds, garlic, and dry red chilies.",
    basePortionPerPax: 0.12,
    portionUnit: "L",
    approxCostPerPax: 18,
    spiceLevel: "MEDIUM",
    tags: ["dal", "andhra", "traditional"],
  },
  "sam-andhra-sambar": {
    id: "sam-andhra-sambar",
    name: "Drumstick & Shallot Sambar",
    category: "Sambar",
    dietary: "VEG",
    description: "Slow-boiled lentils with tender drumsticks, baby pearl onions, and fragrant home-ground sambar spice.",
    basePortionPerPax: 0.15,
    portionUnit: "L",
    approxCostPerPax: 16,
    spiceLevel: "MEDIUM",
    tags: ["sambar", "traditional"],
  },
  "ras-pepper-rasam": {
    id: "ras-pepper-rasam",
    name: "Miriyala Pepper Rasam",
    category: "Sambar",
    dietary: "VEG",
    description: "Digestive broth brewed with crushed black pepper, cumin seeds, garlic, and tamarind.",
    basePortionPerPax: 0.12,
    portionUnit: "L",
    approxCostPerPax: 12,
    spiceLevel: "SPICY",
    tags: ["rasam", "digestive"],
  },

  // Sweets & Desserts
  "swt-gulab-jamun": {
    id: "swt-gulab-jamun",
    name: "Warm Shahi Gulab Jamun",
    category: "Sweet",
    dietary: "VEG",
    description: "Soft khoya dumplings deep-fried and soaked in rosewater and cardamom syrup.",
    basePortionPerPax: 2,
    portionUnit: "pcs",
    approxCostPerPax: 26,
    spiceLevel: "MILD",
    tags: ["sweet", "warm", "traditional"],
  },
  "swt-double-ka-meetha": {
    id: "swt-double-ka-meetha",
    name: "Hyderabadi Double Ka Meetha",
    category: "Sweet",
    dietary: "VEG",
    description: "Fried bread soaked in saffron-infused rabdi and garnished with sliced pistachios and cashews.",
    basePortionPerPax: 0.1,
    portionUnit: "kg",
    approxCostPerPax: 34,
    spiceLevel: "MILD",
    tags: ["sweet", "hyderabadi", "royal"],
  },
  "swt-gajar-halwa": {
    id: "swt-gajar-halwa",
    name: "Ghee Gajar Ka Halwa",
    category: "Sweet",
    dietary: "VEG",
    description: "Slow-roasted red Delhi carrots simmered with condensed milk, pure ghee, and roasted nuts.",
    basePortionPerPax: 0.1,
    portionUnit: "kg",
    approxCostPerPax: 36,
    spiceLevel: "MILD",
    tags: ["sweet", "halwa", "seasonal"],
  },
  "ice-malai-kulfi": {
    id: "ice-malai-kulfi",
    name: "Matka Malai Kulfi",
    category: "Ice Cream",
    dietary: "VEG",
    description: "Traditional frozen dairy dessert on wooden sticks enriched with cardamom and almonds.",
    basePortionPerPax: 1,
    portionUnit: "pcs",
    approxCostPerPax: 25,
    spiceLevel: "MILD",
    tags: ["dessert", "kulfi", "chilled"],
  },
  "ice-vanilla-fudge": {
    id: "ice-vanilla-fudge",
    name: "Vanilla Bean with Hot Chocolate Fudge",
    category: "Ice Cream",
    dietary: "VEG",
    description: "Premium Madagascar vanilla scoop drizzled with hot melted Belgian chocolate sauce.",
    basePortionPerPax: 1,
    portionUnit: "pcs",
    approxCostPerPax: 22,
    spiceLevel: "MILD",
    tags: ["dessert", "icecream"],
  },
};

export const LIVE_COUNTERS_MASTER: LiveCounterAddon[] = [
  {
    id: "live-dosa",
    name: "Live Master Dosa Counter",
    category: "LIVE_STATION",
    pricePerPax: 65,
    minPax: 100,
    description: "Live chefs preparing 5 hot dosa varieties (Ghee Roast, Mysore Masala, Onion Podi, Cheese, Rava) with 3 fresh chutneys and sambar.",
    equipmentNeeded: ["Heavy Duty Gas Tawa", "Chutney Dispensers", "LPG Cylinders", "Batter Dispenser"],
    dietary: "VEG",
  },
  {
    id: "live-pani-puri",
    name: "Chaat & Pani Puri Station",
    category: "LIVE_STATION",
    pricePerPax: 45,
    minPax: 100,
    description: "Live station serving 3 flavored pani waters (Hing Jeera, Tangy Pudina, Sweet Dates), Dahi Puri, and Papdi Sev Chaat.",
    equipmentNeeded: ["Earthen Matkas", "Chaat Counters", "Purified Ice Machine"],
    dietary: "VEG",
  },
  {
    id: "live-tawa-fry",
    name: "Live Tawa Fish & Kebabs",
    category: "LIVE_STATION",
    pricePerPax: 110,
    minPax: 150,
    description: "Fresh catch Vanjaram/Apollo fish and chicken skewers pan-seared live on cast iron tawas with onion rings and lemon wedges.",
    equipmentNeeded: ["Cast Iron Commercial Tawa", "Marination Chiller", "High-Flame Burners"],
    dietary: "NON_VEG",
  },
  {
    id: "live-arabian-mandi",
    name: "Arabian Mandi Experience Station",
    category: "SPECIAL_DISH",
    pricePerPax: 95,
    minPax: 200,
    description: "Grand communal Mandi platters with slow-roasted lamb shank or chicken, smoked basmati rice, dakkoos sauce, and roasted dry fruits.",
    equipmentNeeded: ["Large Mandi Trays", "Charcoal Smoker Box", "Carving Station"],
    dietary: "NON_VEG",
  },
  {
    id: "live-juice-bar",
    name: "Fresh Sugarcane & Juice Bar",
    category: "BEVERAGE_BAR",
    pricePerPax: 40,
    minPax: 100,
    description: "Live sugarcane press with ginger/lemon plus tender coconut water tapped fresh for guests.",
    equipmentNeeded: ["Stainless Steel Sugarcane Crusher", "Coconut Opener Station", "Ice Barrels"],
    dietary: "VEG",
  },
  {
    id: "live-dessert-falooda",
    name: "Artisan Falooda & Kulfi Bar",
    category: "DESSERT_BAR",
    pricePerPax: 50,
    minPax: 100,
    description: "Interactive Royal Falooda station with basil seeds (sabja), rose milk, vermicelli, rabdi, and choice of 3 artisanal kulfis.",
    equipmentNeeded: ["Glass Display Freezers", "Falooda Dispensers", "Nut Bowls"],
    dietary: "VEG",
  },
];

export const SMART_MENU_TEMPLATES: SmartMenuTemplate[] = [
  {
    id: "wedding-lunch-premium",
    name: "Wedding Lunch – Premium Feast",
    description: "Grand banquet menu engineered for high-profile South Indian weddings with comprehensive vegetarian and non-vegetarian luxury spreads.",
    applicableEventTypes: ["WEDDING", "RECEPTION"],
    applicableMealTypes: ["LUNCH", "DINNER"],
    basePricePerPax: 850,
    categoryRules: [
      {
        category: "Welcome Drink",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["wd-fruit-punch"],
          MENU_ITEMS_MASTER["wd-badam-milk"],
          MENU_ITEMS_MASTER["wd-mango-lassi"],
          MENU_ITEMS_MASTER["wd-mint-cooler"],
        ],
      },
      {
        category: "Starter",
        minSelections: 2,
        maxSelections: 2,
        availableItems: [
          MENU_ITEMS_MASTER["str-chicken-65"],
          MENU_ITEMS_MASTER["str-paneer-tikka"],
          MENU_ITEMS_MASTER["str-apollo-fish"],
          MENU_ITEMS_MASTER["str-veg-spring-roll"],
          MENU_ITEMS_MASTER["str-corn-pepper"],
        ],
      },
      {
        category: "Biryani",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["bir-chicken-dum"],
          MENU_ITEMS_MASTER["bir-mutton-dum"],
          MENU_ITEMS_MASTER["bir-veg-dum"],
          MENU_ITEMS_MASTER["rc-bagara"],
        ],
      },
      {
        category: "Breads",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["brd-butter-naan"],
          MENU_ITEMS_MASTER["brd-rumali"],
        ],
      },
      {
        category: "Curry",
        minSelections: 2,
        maxSelections: 2,
        availableItems: [
          MENU_ITEMS_MASTER["cur-butter-chicken"],
          MENU_ITEMS_MASTER["cur-paneer-butter-masala"],
          MENU_ITEMS_MASTER["cur-kadai-paneer"],
          MENU_ITEMS_MASTER["cur-veg-kolhapuri"],
          MENU_ITEMS_MASTER["cur-dal-makhani"],
        ],
      },
      {
        category: "Rice",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["rc-steamed-rice"],
        ],
      },
      {
        category: "Dal",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["dal-tomato-pappu"],
        ],
      },
      {
        category: "Sambar",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["sam-andhra-sambar"],
          MENU_ITEMS_MASTER["ras-pepper-rasam"],
        ],
      },
      {
        category: "Sweet",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["swt-gulab-jamun"],
          MENU_ITEMS_MASTER["swt-double-ka-meetha"],
          MENU_ITEMS_MASTER["swt-gajar-halwa"],
        ],
      },
      {
        category: "Ice Cream",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["ice-malai-kulfi"],
          MENU_ITEMS_MASTER["ice-vanilla-fudge"],
        ],
      },
    ],
  },
  {
    id: "wedding-lunch-basic",
    name: "Wedding Lunch – Classic Traditional",
    description: "Balanced, cost-effective traditional marriage feast focusing on high-velocity core dishes and authentic flavors.",
    applicableEventTypes: ["WEDDING", "HOUSEWARMING", "ENGAGEMENT"],
    applicableMealTypes: ["LUNCH"],
    basePricePerPax: 650,
    categoryRules: [
      {
        category: "Welcome Drink",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["wd-fruit-punch"],
          MENU_ITEMS_MASTER["wd-mint-cooler"],
        ],
      },
      {
        category: "Starter",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["str-chicken-65"],
          MENU_ITEMS_MASTER["str-veg-spring-roll"],
        ],
      },
      {
        category: "Biryani",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["bir-chicken-dum"],
          MENU_ITEMS_MASTER["bir-veg-dum"],
        ],
      },
      {
        category: "Curry",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["cur-butter-chicken"],
          MENU_ITEMS_MASTER["cur-paneer-butter-masala"],
        ],
      },
      {
        category: "Rice",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["rc-steamed-rice"],
        ],
      },
      {
        category: "Dal",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["dal-tomato-pappu"],
        ],
      },
      {
        category: "Sambar",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["sam-andhra-sambar"],
        ],
      },
      {
        category: "Sweet",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["swt-gulab-jamun"],
          MENU_ITEMS_MASTER["swt-double-ka-meetha"],
        ],
      },
    ],
  },
  {
    id: "corporate-executive",
    name: "Corporate Executive Buffet",
    description: "Streamlined high-productivity buffet tailored for annual tech summits, conferences, and corporate galas.",
    applicableEventTypes: ["CORPORATE"],
    applicableMealTypes: ["LUNCH", "DINNER"],
    basePricePerPax: 720,
    categoryRules: [
      {
        category: "Welcome Drink",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["wd-fruit-punch"],
          MENU_ITEMS_MASTER["wd-mint-cooler"],
        ],
      },
      {
        category: "Starter",
        minSelections: 2,
        maxSelections: 2,
        availableItems: [
          MENU_ITEMS_MASTER["str-chicken-65"],
          MENU_ITEMS_MASTER["str-paneer-tikka"],
          MENU_ITEMS_MASTER["str-corn-pepper"],
        ],
      },
      {
        category: "Biryani",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["bir-chicken-dum"],
          MENU_ITEMS_MASTER["bir-veg-dum"],
        ],
      },
      {
        category: "Breads",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["brd-butter-naan"],
        ],
      },
      {
        category: "Curry",
        minSelections: 2,
        maxSelections: 2,
        availableItems: [
          MENU_ITEMS_MASTER["cur-butter-chicken"],
          MENU_ITEMS_MASTER["cur-paneer-butter-masala"],
          MENU_ITEMS_MASTER["cur-dal-makhani"],
        ],
      },
      {
        category: "Sweet",
        minSelections: 1,
        maxSelections: 1,
        availableItems: [
          MENU_ITEMS_MASTER["swt-gulab-jamun"],
          MENU_ITEMS_MASTER["ice-vanilla-fudge"],
        ],
      },
    ],
  },
];
